# Generated by Django 4.2.7 on 2025-08-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageExchangePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('greetings', '挨拶'), ('food', '料理'), ('shopping', '買い物'), ('transport', '交通'), ('daily', '日常生活'), ('business', '仕事'), ('travel', '旅行'), ('emergency', '緊急')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '上級')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnamese_text', models.CharField(max_length=200)),
                ('japanese_translation', models.CharField(max_length=200)),
                ('english_translation', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lesson_audio/')),
                ('pronunciation_guide', models.CharField(blank=True, max_length=200)),
                ('usage_note', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('japanese_to_vietnamese', 'Japanese learning Vietnamese'), ('vietnamese_to_japanese', 'Vietnamese learning Japanese'), ('both', 'Both languages')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preferred_city', models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ'), ('any', 'Any city')], max_length=20)),
                ('meeting_preference', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('flexible', 'Flexible')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VietnamesePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greetings', 'Greetings'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('emergency', 'Emergency'), ('daily', 'Daily Life'), ('business', 'Business'), ('travel', 'Travel')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('vietnamese_text', models.CharField(max_length=200)),
                ('japanese_translation', models.CharField(max_length=200)),
                ('english_translation', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='phrase_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
