# Generated by Django 4.2.7 on 2025-08-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_creation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_partner_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonphrase',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='event_creation.lesson'),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='cafe_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_creation.cafelocation'),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='japanese_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_creation.vietnamesephrase'),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='vietnamese_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vietnamese_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
