# Generated by Django 4.2.7 on 2025-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelocation',
            name='address',
            field=models.TextField(help_text='Full address'),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], help_text='City for filtering locations', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the location'),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='name',
            field=models.CharField(help_text='Cafe or location name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Pronunciation audio', null=True, upload_to='phrase_audio/'),
        ),
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='category',
            field=models.CharField(choices=[('greetings', 'Greetings'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('emergency', 'Emergency'), ('daily', 'Daily Life'), ('business', 'Business'), ('travel', 'Travel')], help_text='Topic category', max_length=20),
        ),
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Learning difficulty level', max_length=15),
        ),
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='english_translation',
            field=models.CharField(help_text='English translation for reference', max_length=200),
        ),
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='japanese_translation',
            field=models.CharField(help_text='Japanese translation', max_length=200),
        ),
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='vietnamese_text',
            field=models.CharField(help_text='Original Vietnamese phrase', max_length=200),
        ),
    ]
