# Generated by Django 4.2.7 on 2025-08-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0003_alter_cafelocation_address_alter_cafelocation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('greetings', 'Chào hỏi (挨拶)'), ('self_introduction', 'Giới thiệu bản thân (自己紹介)'), ('asking_directions', 'Hỏi đường (道を尋ねる)'), ('shopping', 'Mua sắm (買い物)'), ('restaurant', 'Nhà hàng / gọi món (レストラン)'), ('transportation', 'Giao thông / đi lại (交通)'), ('weather', 'Thời tiết (天気)'), ('family', 'Gia đình (家族)'), ('health_emergency', 'Sức khỏe / trường hợp khẩn cấp (健康・緊急)'), ('time_schedule', 'Thời gian / lịch trình (時間・予定)')], max_length=25),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Câu hỏi trắc nghiệm')),
                ('option_a', models.CharField(help_text='Lựa chọn A', max_length=100)),
                ('option_b', models.CharField(help_text='Lựa chọn B', max_length=100)),
                ('option_c', models.CharField(help_text='Lựa chọn C', max_length=100)),
                ('option_d', models.CharField(help_text='Lựa chọn D', max_length=100)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Đáp án đúng', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Giải thích đáp án')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='event_creation.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
