# Generated by Django 4.2.7 on 2025-08-11 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_creation', '0003_alter_cafelocation_address_alter_cafelocation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageexchangepost',
            name='japanese_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='japanese_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='languageexchangepost',
            name='vietnamese_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vietnamese_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
