# Generated by Django 4.2.7 on 2025-08-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0004_alter_lesson_category_quizquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FillInBlankExercise',
        ),
    ]
