# Generated by Django 4.2.7 on 2025-08-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0004_alter_languageexchangepost_japanese_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageexchangepost',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_creation.vietnamesephrase'),
        ),
    ]
