# Generated by Django 4.2.7 on 2025-08-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0005_alter_languageexchangepost_phrase'),
        ('event_creation', '0006_conversationexample_theorysection_theoryphrase_and_more'),
    ]

    operations = [
    ]
