# Generated by Django 4.2.7 on 2025-08-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0005_alter_lesson_category_quizquestion'),
        ('event_creation', '0006_alter_languageexchangepost_phrase'),
    ]

    operations = [
    ]
