# Generated by Django 4.2.7 on 2025-08-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_creation', '0007_merge_20250812_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề đoạn hội thoại', max_length=200)),
                ('description', models.TextField(help_text='Mô tả tình huống')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['theory_section', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='languageexchangepost',
            name='vietnamese_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vietnamese_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TheorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề phần lý thuyết', max_length=200)),
                ('description', models.TextField(help_text='Mô tả phần lý thuyết')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_sections', to='event_creation.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TheoryPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnamese_text', models.CharField(help_text='Câu tiếng Việt', max_length=200)),
                ('japanese_translation', models.CharField(help_text='Bản dịch tiếng Nhật', max_length=200)),
                ('english_translation', models.CharField(help_text='Bản dịch tiếng Anh', max_length=200)),
                ('pronunciation_guide', models.CharField(blank=True, help_text='Hướng dẫn phát âm', max_length=200)),
                ('usage_note', models.TextField(blank=True, help_text='Ghi chú cách sử dụng')),
                ('is_essential', models.BooleanField(default=False, help_text='Câu nói cần thiết')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theory_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='event_creation.theorysection')),
            ],
            options={
                'ordering': ['theory_section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ConversationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('tutor', 'TUTOR'), ('student', 'STUDENT'), ('person_a', 'PERSON A'), ('person_b', 'PERSON B')], help_text='Người nói', max_length=50)),
                ('vietnamese_text', models.CharField(help_text='Nội dung tiếng Việt', max_length=300)),
                ('japanese_translation', models.CharField(help_text='Bản dịch tiếng Nhật', max_length=300)),
                ('english_translation', models.CharField(help_text='Bản dịch tiếng Anh', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự trong hội thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='event_creation.conversationexample')),
            ],
            options={
                'ordering': ['conversation', 'order'],
            },
        ),
        migrations.AddField(
            model_name='conversationexample',
            name='theory_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='event_creation.theorysection'),
        ),
    ]
