# Generated by Django 4.2.7 on 2025-08-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0008_conversationexample_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafelocation',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='cafe_type',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('library', 'Library'), ('coworking', 'Co-working Space'), ('park', 'Public Park'), ('mall', 'Shopping Mall'), ('other', 'Other')], default='cafe', help_text='Type of meeting location', max_length=20),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Has parking available'),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='has_wifi',
            field=models.BooleanField(default=True, help_text='Has free WiFi'),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='is_24h',
            field=models.BooleanField(default=False, help_text='Open 24 hours'),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='is_quiet',
            field=models.BooleanField(default=False, help_text='Suitable for quiet study/conversation'),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='e.g., 7:00 AM - 10:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='price_range',
            field=models.CharField(choices=[('budget', 'Budget (Under 50k VND)'), ('moderate', 'Moderate (50k-150k VND)'), ('premium', 'Premium (Over 150k VND)')], default='moderate', help_text='Price range for the location', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ'), ('nhatrang', 'Nha Trang'), ('dalat', 'Đà Lạt'), ('hue', 'Huế'), ('quangninh', 'Quảng Ninh'), ('thainguyen', 'Thái Nguyên'), ('vinhphuc', 'Vĩnh Phúc'), ('bacninh', 'Bắc Ninh'), ('haiduong', 'Hải Dương'), ('hungyen', 'Hưng Yên'), ('thaibinh', 'Thái Bình'), ('namdinh', 'Nam Định'), ('ninhbinh', 'Ninh Bình'), ('thanhhoa', 'Thanh Hóa'), ('nghean', 'Nghệ An'), ('hatinh', 'Hà Tĩnh'), ('quangbinh', 'Quảng Bình'), ('quangtri', 'Quảng Trị'), ('binhdinh', 'Bình Định'), ('phuyen', 'Phú Yên'), ('khanhhoa', 'Khánh Hòa'), ('ninhthuan', 'Ninh Thuận'), ('binhthuan', 'Bình Thuận'), ('dongnai', 'Đồng Nai'), ('binhduong', 'Bình Dương'), ('tayninh', 'Tây Ninh'), ('binhphuoc', 'Bình Phước'), ('lamdong', 'Lâm Đồng'), ('bariavungtau', 'Bà Rịa - Vũng Tàu'), ('longan', 'Long An'), ('tiengiang', 'Tiền Giang'), ('bentre', 'Bến Tre'), ('travinh', 'Trà Vinh'), ('vinhlong', 'Vĩnh Long'), ('socang', 'Sóc Trăng'), ('kiengiang', 'Kiên Giang'), ('camau', 'Cà Mau'), ('baclieu', 'Bạc Liêu'), ('angiang', 'An Giang'), ('dongthap', 'Đồng Tháp')], help_text='City for filtering locations', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='preferred_city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ'), ('nhatrang', 'Nha Trang'), ('dalat', 'Đà Lạt'), ('hue', 'Huế'), ('quangninh', 'Quảng Ninh'), ('thainguyen', 'Thái Nguyên'), ('vinhphuc', 'Vĩnh Phúc'), ('bacninh', 'Bắc Ninh'), ('haiduong', 'Hải Dương'), ('hungyen', 'Hưng Yên'), ('thaibinh', 'Thái Bình'), ('namdinh', 'Nam Định'), ('ninhbinh', 'Ninh Bình'), ('thanhhoa', 'Thanh Hóa'), ('nghean', 'Nghệ An'), ('hatinh', 'Hà Tĩnh'), ('quangbinh', 'Quảng Bình'), ('quangtri', 'Quảng Trị'), ('binhdinh', 'Bình Định'), ('phuyen', 'Phú Yên'), ('khanhhoa', 'Khánh Hòa'), ('ninhthuan', 'Ninh Thuận'), ('binhthuan', 'Bình Thuận'), ('dongnai', 'Đồng Nai'), ('binhduong', 'Bình Dương'), ('tayninh', 'Tây Ninh'), ('binhphuoc', 'Bình Phước'), ('lamdong', 'Lâm Đồng'), ('bariavungtau', 'Bà Rịa - Vũng Tàu'), ('longan', 'Long An'), ('tiengiang', 'Tiền Giang'), ('bentre', 'Bến Tre'), ('travinh', 'Trà Vinh'), ('vinhlong', 'Vĩnh Long'), ('socang', 'Sóc Trăng'), ('kiengiang', 'Kiên Giang'), ('camau', 'Cà Mau'), ('baclieu', 'Bạc Liêu'), ('angiang', 'An Giang'), ('dongthap', 'Đồng Tháp'), ('any', 'Any city')], help_text='Preferred city for meeting', max_length=20),
        ),
    ]
