# Generated by Django 4.2.7 on 2025-08-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0009_alter_cafelocation_options_cafelocation_cafe_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafelocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='cafe_type',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='is_24h',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='is_quiet',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], help_text='City for filtering locations', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='preferred_city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ'), ('any', 'Any city')], max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(help_text='Actual meeting date and time')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Meeting duration in minutes')),
                ('japanese_user_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from Japanese user (1-5 stars)', null=True)),
                ('japanese_user_feedback', models.TextField(blank=True, help_text='Feedback from Japanese user')),
                ('japanese_user_rated_at', models.DateTimeField(blank=True, null=True)),
                ('vietnamese_user_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from Vietnamese user (1-5 stars)', null=True)),
                ('vietnamese_user_feedback', models.TextField(blank=True, help_text='Feedback from Vietnamese user')),
                ('vietnamese_user_rated_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_outcome', models.CharField(choices=[('successful', 'Successful'), ('partially_successful', 'Partially Successful'), ('unsuccessful', 'Unsuccessful'), ('cancelled', 'Cancelled')], default='successful', help_text='Overall outcome of the meeting', max_length=20)),
                ('points_earned_japanese', models.PositiveIntegerField(default=0, help_text='Points earned by Japanese user')),
                ('points_earned_vietnamese', models.PositiveIntegerField(default=0, help_text='Points earned by Vietnamese user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_history', to='event_creation.languageexchangepost')),
            ],
            options={
                'verbose_name': 'Meeting History',
                'verbose_name_plural': 'Meeting Histories',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
