# Generated by Django 4.2.7 on 2025-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0009_alter_cafelocation_options_cafelocation_cafe_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafelocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='cafe_type',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='is_24h',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='is_quiet',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='cafelocation',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], help_text='City for filtering locations', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='preferred_city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ'), ('any', 'Any city')], max_length=20),
        ),
    ]
