# Generated by Django 4.2.7 on 2025-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0010_alter_cafelocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageexchangepost',
            name='status',
            field=models.CharField(choices=[('active', '募集中'), ('matched', 'マッチ済み'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='active', max_length=15),
        ),
    ]
