# Generated by Django 4.2.7 on 2025-08-13 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_creation', '0010_alter_cafelocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(help_text='Ngày diễn ra phiên học')),
                ('session_duration', models.PositiveIntegerField(help_text='Thời lượng phiên học (phút)')),
                ('session_type', models.CharField(choices=[('online', 'Trực tuyến'), ('offline', 'Trực tiếp')], default='offline', max_length=20)),
                ('japanese_rating', models.PositiveIntegerField(help_text='Điểm đánh giá từ 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('japanese_comment', models.TextField(blank=True, help_text='Nhận xét từ người Nhật')),
                ('japanese_rating_date', models.DateTimeField(auto_now_add=True)),
                ('vietnamese_rating', models.PositiveIntegerField(blank=True, help_text='Điểm đánh giá từ 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('vietnamese_comment', models.TextField(blank=True, help_text='Nhận xét từ người Việt')),
                ('vietnamese_rating_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không tham gia')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú bổ sung về phiên học')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('japanese_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_connections', to=settings.AUTH_USER_MODEL)),
                ('language_exchange_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_creation.languageexchangepost')),
                ('partner_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_creation.partnerrequest')),
                ('vietnamese_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vietnamese_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử kết nối',
                'verbose_name_plural': 'Lịch sử kết nối',
                'ordering': ['-session_date'],
                'unique_together': {('japanese_user', 'vietnamese_user', 'session_date')},
            },
        ),
        migrations.DeleteModel(
            name='MeetingHistory',
        ),
    ]
