# Generated by Django 4.2.7 on 2025-08-13 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0011_connectionhistory_delete_meetinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='japanese_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Điểm đánh giá từ 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
