# Generated by Django 4.2.7 on 2025-08-14 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_creation', '0011_alter_languageexchangepost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageexchangepost',
            name='japanese_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_japanese_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='user_type',
            field=models.CharField(choices=[('vietnamese', 'Vietnamese User'), ('japanese', 'Japanese User')], default='vietnamese', help_text='Type of user who created this post', max_length=15),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='vietnamese_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_vietnamese_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='languageexchangepost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='languageexchangepost',
            name='vietnamese_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vietnamese_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
