# Generated by Django 4.2.7 on 2025-08-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0012_alter_connectionhistory_japanese_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='vietnamese_comment',
            field=models.TextField(blank=True, help_text='Nhận xét từ người Việt', null=True),
        ),
    ]
