# Generated by Django 4.2.7 on 2025-08-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0012_languageexchangepost_japanese_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vietnamesephrase',
            name='category',
            field=models.CharField(choices=[('greetings', 'Greetings'), ('family', 'Family'), ('health', 'Health'), ('time', 'Time'), ('weather', 'Weather'), ('directions', 'Directions'), ('self_intro', 'Self Introduction'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('emergency', 'Emergency'), ('daily', 'Daily Life'), ('business', 'Business'), ('travel', 'Travel')], help_text='Topic category', max_length=20),
        ),
    ]
