# Generated by Django 4.2.7 on 2025-08-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_creation', '0012_culturallocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationline',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='lessonphrase',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='theoryphrase',
            name='theory_section',
        ),
        migrations.RemoveField(
            model_name='theorysection',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='languageexchangepost',
            name='vietnamese_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vietnamese_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConversationExample',
        ),
        migrations.DeleteModel(
            name='ConversationLine',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonPhrase',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='TheoryPhrase',
        ),
        migrations.DeleteModel(
            name='TheorySection',
        ),
    ]
