# Generated by Django 4.2.7 on 2025-08-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0013_remove_conversationline_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageexchangepost',
            name='applicant_text',
        ),
        migrations.RemoveField(
            model_name='languageexchangepost',
            name='poster_text',
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='japanese_learning_phrases',
            field=models.ManyToManyField(blank=True, help_text='Vietnamese phrases that Japanese users want to learn', related_name='japanese_learning_posts', to='event_creation.vietnamesephrase'),
        ),
        migrations.AddField(
            model_name='languageexchangepost',
            name='vietnamese_learning_phrases',
            field=models.ManyToManyField(blank=True, help_text='Japanese phrases that Vietnamese users want to learn', related_name='vietnamese_learning_posts', to='event_creation.vietnamesephrase'),
        ),
    ]
