# Generated by Django 4.2.7 on 2025-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0013_alter_connectionhistory_vietnamese_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='japanese_comment',
            field=models.TextField(blank=True, help_text='Nhận xét từ người Nhật', null=True),
        ),
    ]
