# Generated by Django 4.2.7 on 2025-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0014_alter_connectionhistory_japanese_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Ghi chú bổ sung về phiên học', null=True),
        ),
    ]
