# Generated by Django 4.2.7 on 2025-08-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0014_remove_languageexchangepost_applicant_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageexchangepost',
            name='accepted_phrase',
            field=models.ForeignKey(blank=True, help_text='Phrase chosen by the person who accepted this post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_posts', to='event_creation.vietnamesephrase'),
        ),
    ]
