# Generated by Django 4.2.7 on 2025-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0015_alter_connectionhistory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('waiting_japanese_rating', 'Chờ đánh giá từ người Nhật'), ('waiting_vietnamese_rating', 'Chờ đánh giá từ người Việt'), ('fully_rated', 'Đã đánh giá đầy đủ'), ('cancelled', 'Đã hủy'), ('no_show', 'Không tham gia')], default='active', max_length=30),
        ),
    ]
