# Generated by Django 4.2.7 on 2025-08-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0015_languageexchangepost_accepted_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the conversation', max_length=200)),
                ('vietnamese_title', models.CharField(help_text='Vietnamese title', max_length=200)),
                ('japanese_title', models.CharField(help_text='Japanese title', max_length=200)),
                ('line_1_teacher', models.CharField(help_text='First line from teacher', max_length=500)),
                ('line_1_student', models.CharField(help_text='First line from student', max_length=500)),
                ('line_2_teacher', models.CharField(help_text='Second line from teacher', max_length=500)),
                ('line_2_student', models.CharField(help_text='Second line from student', max_length=500)),
                ('line_3_teacher', models.CharField(help_text='Third line from teacher', max_length=500)),
                ('line_3_student', models.CharField(help_text='Third line from student', max_length=500)),
                ('line_1_teacher_jp', models.CharField(help_text='Japanese translation of first teacher line', max_length=500)),
                ('line_1_student_jp', models.CharField(help_text='Japanese translation of first student line', max_length=500)),
                ('line_2_teacher_jp', models.CharField(help_text='Japanese translation of second teacher line', max_length=500)),
                ('line_2_student_jp', models.CharField(help_text='Japanese translation of second student line', max_length=500)),
                ('line_3_teacher_jp', models.CharField(help_text='Japanese translation of third teacher line', max_length=500)),
                ('line_3_student_jp', models.CharField(help_text='Japanese translation of third student line', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_examples', to='event_creation.vietnamesephrase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
