# Generated by Django 4.2.7 on 2025-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about yourself', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], help_text='City for language exchange meetups', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Must be 18+ to register', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, help_text='Your hobbies and interests', max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(choices=[('vietnamese', 'Vietnamese'), ('japanese', 'Japanese')], help_text='Vietnamese or Japanese', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(default='en', help_text='Interface language preference', max_length=10),
        ),
    ]
