# Generated by Django 4.2.7 on 2025-08-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_customuser_bio_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=0, help_text="User's current point"),
        ),
    ]
