# Generated by Django 4.2.7 on 2025-08-13 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_customuser_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('coffee', 'Coffee Shop Discount'), ('restaurant', 'Restaurant Discount'), ('shopping', 'Shopping Discount'), ('transport', 'Transport Discount'), ('entertainment', 'Entertainment Discount')], max_length=20)),
                ('discount_percentage', models.IntegerField(help_text='Discount percentage (e.g., 10 for 10%)')),
                ('points_required', models.IntegerField(help_text='Points required to exchange for this voucher')),
                ('description', models.TextField(help_text='Description of the discount offer')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='Expiry date of the voucher')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=10)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Voucher',
                'verbose_name_plural': 'Discount Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
