# Generated by Django 5.2.4 on 2025-08-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vietnamese_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('history_story', models.TextField(help_text='Câu chuyện lịch sử hoặc phong tục')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('region', models.CharField(help_text='Vùng miền', max_length=100)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Dễ'), (2, 'Trung bình'), (3, 'Khó')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderingPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnamese', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(max_length=200)),
                ('context', models.TextField(help_text='Tình huống sử dụng')),
                ('order', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_phrases', to='food_culture.traditionalfood')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vietnamese_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('is_allergen', models.BooleanField(default=False, help_text='Có thể gây dị ứng')),
                ('allergen_warning', models.TextField(blank=True, help_text='Cảnh báo dị ứng')),
                ('description', models.TextField(blank=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food_culture.traditionalfood')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Từ khóa trong bài học', max_length=100)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talk.lesson')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_culture.traditionalfood')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('table_manners', 'Phép tắc bàn ăn'), ('chopsticks', 'Cách dùng đũa'), ('festival', 'Phong tục lễ Tết'), ('general', 'Văn hóa chung')], max_length=20)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultural_tips/')),
                ('order', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_tips', to='food_culture.traditionalfood')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
