# Generated by Django 5.2.4 on 2025-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_culture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh minh họa cho nguyên liệu', null=True, upload_to='ingredient_images/'),
        ),
    ]
