# Generated by Django 4.2.7 on 2025-08-11 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_creation', '0003_alter_cafelocation_address_alter_cafelocation_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_system', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the chat room was created'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the chat room is still active'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='partner_request',
            field=models.OneToOneField(blank=True, help_text='Associated partner request', null=True, on_delete=django.db.models.deletion.CASCADE, to='event_creation.partnerrequest'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='post',
            field=models.OneToOneField(blank=True, help_text='Associated language exchange post', null=True, on_delete=django.db.models.deletion.CASCADE, to='event_creation.languageexchangepost'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(help_text='The chat room this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_system.chatroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='The message text content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the recipient has read the message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the message was sent'),
        ),
    ]
