# Generated by Django 5.2.4 on 2025-08-06 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='group_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhóm chat',
                'verbose_name_plural': 'Nhóm chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.groupchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('city', models.CharField(choices=[('hanoi', 'Hà Nội'), ('hcm', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], max_length=20, verbose_name='Thành phố')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm cụ thể')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('time', models.TimeField(verbose_name='Giờ')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Thời lượng (giờ)')),
                ('estimated_cost', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Chi phí dự kiến (VNĐ)')),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Số người tối đa')),
                ('current_participants', models.IntegerField(default=1, verbose_name='Số người hiện tại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài đăng',
                'verbose_name_plural': 'Bài đăng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupchat',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='main.post'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('birth_date', models.DateField(verbose_name='Ngày sinh')),
                ('city', models.CharField(choices=[('hanoi', 'Hà Nội'), ('hcm', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('cantho', 'Cần Thơ')], max_length=20, verbose_name='Thành phố')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Giới thiệu')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Lời nhắn')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.post')),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Đơn ứng tuyển',
                'unique_together': {('applicant', 'post')},
            },
        ),
    ]
